1. Import Libraries

In [1]:
# Import required libraries
import pandas as pd
import numpy as np

2. Load Dataset

In [2]:
# Load the dataset
df = pd.read_csv("AdventureWorks Product Subcategories Lookup.csv", encoding="ISO-8859-1")

# Preview dataset
df.head()

   ProductSubcategoryKey  SubcategoryName  ProductCategoryKey
0                      1   Mountain Bikes                   1
1                      2       Road Bikes                   1
2                      3    Touring Bikes                   1
3                      4       Handlebars                   2
4                      5  Bottom Brackets                   2

3. Before Dataset Overview

In [3]:
# Check dataset structure
df.info()

# Check number of rows and columns
print(df.shape)

# Statistical summary
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37 entries, 0 to 36
Data columns (total 3 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ProductSubcategoryKey  37 non-null     int64
 1   SubcategoryName        37 non-null     object
 2   ProductCategoryKey     37 non-null     int64
dtypes: int64(2), object(1)
memory usage: 1020.0+ bytes
(37, 3)

       ProductSubcategoryKey  ProductCategoryKey
count              37.000000           37.000000
mean               19.000000            2.783784
std                10.824355            1.003747
min                 1.000000            1.000000
25%                10.000000            2.000000
50%                19.000000            3.000000
75%                28.000000            4.000000
max                37.000000            4.000000

4. Check Duplicate Rows

In [ ]:
# Check duplicate 
df.duplicated().sum()

np.int64(0)

5. Check Missing Values

In [5]:
# Check missing values
df.isnull().sum()

ProductSubcategoryKey    0
SubcategoryName          0
ProductCategoryKey       0
dtype: int64

6. Fix Data Types

In [7]:
# Clean and convert to category
df['SubcategoryName'] = df['SubcategoryName'].astype('category')
df.dtypes

ProductSubcategoryKey       int64
SubcategoryName          category
ProductCategoryKey          int64
dtype: object

7. Clean Text Columns

In [19]:
# Standardize capitalization
df['SubcategoryName'] = df['SubcategoryName'].str.strip().str.title()

# Convert back to categorical type
df['SubcategoryName'] = df['SubcategoryName'].astype('category')

# Verify
print(df.dtypes)
print(df.head())

ProductSubcategoryKey       int64
SubcategoryName          category
ProductCategoryKey          int64
dtype: object
   ProductSubcategoryKey  SubcategoryName  ProductCategoryKey
0                      1   Mountain Bikes                   1
1                      2       Road Bikes                   1
2                      3    Touring Bikes                   1
3                      4       Handlebars                   2
4                      5  Bottom Brackets                   2

8. check unique categories

In [20]:
# Count unique subcategories
print("No. of unique subcategories : " ,df['SubcategoryName'].nunique())

#To see the actual unique values
print(df['SubcategoryName'].unique())

No. of unique subcategories :  37
['Mountain Bikes', 'Road Bikes', 'Touring Bikes', 'Handlebars', 'Bottom Brackets', ..., 'Lights', 'Locks', 'Panniers', 'Pumps', 'Tires And Tubes']
Length: 37
Categories (37, object): ['Bib-Shorts', 'Bike Racks', 'Bike Stands', 'Bottles And Cages', ..., 'Touring Bikes', 'Touring Frames', 'Vests', 'Wheels']

9. After Data cleaning

In [21]:
# 1️.Check Missing Values
print(df.isnull().sum())

# 2.Check Duplicate Rows
print(df.duplicated().sum())

# 3.Verify Final Dataset Shape
print(df.shape)

# 4.Datatype
print(df.dtypes)

# 5.Data preview
print(df.head(5))

ProductSubcategoryKey    0
SubcategoryName          0
ProductCategoryKey       0
dtype: int64
0
(37, 3)
ProductSubcategoryKey       int64
SubcategoryName          category
ProductCategoryKey          int64
dtype: object
   ProductSubcategoryKey  SubcategoryName  ProductCategoryKey
0                      1   Mountain Bikes                   1
1                      2       Road Bikes                   1
2                      3    Touring Bikes                   1
3                      4       Handlebars                   2
4                      5  Bottom Brackets                   2

10. Save Cleaned Dataset

In [22]:
df.to_csv("Cleaned_Productsubcategory_Data.csv", index=False)