# Data Cleaning Notebook

1. Import libraries

In [ ]:
# Import libraries
import pandas as pd
import numpy as np

2. Load Dataset

In [4]:
# Load the dataset
df = pd.read_csv("AdventureWorks Sales Data 2020.csv", encoding="ISO-8859-1")

# Preview dataset
df.head()

,OrderDate,StockDate,OrderNumber,ProductKey,CustomerKey,TerritoryKey,OrderLineItem,OrderQuantity
0,2020-01-01,2019-09-21,SO45080,332,14657,1,1,1
1,2020-01-01,2019-12-05,SO45079,312,29255,4,1,1
2,2020-01-01,2019-10-29,SO45082,350,11455,9,1,1
3,2020-01-01,2019-11-16,SO45081,338,26782,6,1,1
4,2020-01-02,2019-12-15,SO45083,312,14947,10,1,1

3. Check Duplicate Rows

In [8]:
# Check duplicate rows
df.duplicated().sum()

np.int64(0)

4. Check Missing Values

In [6]:
# Check missing values
df.isnull().sum()

OrderDate        0
StockDate        0
OrderNumber      0
ProductKey       0
CustomerKey      0
TerritoryKey     0
OrderLineItem    0
OrderQuantity    0
dtype: int64

5. Fix Data Types

In [20]:
# Step 1: Check original datatypes ---
print("Before conversion:")
print(df.info())

# Step 2: Convert datatypes ---
df['OrderDate'] = df['OrderDate'].astype('datetime64[s]')
df['StockDate'] = df['StockDate'].astype('datetime64[s]')

# Step 3: Check datatypes after conversion ---
print("\nAfter conversion:")
print(df.info())

Before conversion:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2630 entries, 0 to 2629
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   OrderDate      2630 non-null   object
 1   StockDate      2630 non-null   object
 2   OrderNumber    2630 non-null   object
 3   ProductKey     2630 non-null   int64
 4   CustomerKey    2630 non-null   int64
 5   TerritoryKey   2630 non-null   int64
 6   OrderLineItem  2630 non-null   int64
 7   OrderQuantity  2630 non-null   int64
dtypes: int64(5), object(3)
memory usage: 164.5+ KB
None

After conversion:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2630 entries, 0 to 2629
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   OrderDate      2630 non-null   datetime64[s]
 1   StockDate      2630 non-null   datetime64[s]
 2   OrderNumber    2630 non-null   object
 3   ProductKey     2630 non-null   int64
 4   CustomerKey    2630 non-null   int64
 5   TerritoryKey   2630 non-null   int64
 6   OrderLineItem  2630 non-null   int64
 7   OrderQuantity  2630 non-null   int64
dtypes: datetime64[s](2), int64(5), object(1)
memory usage: 164.5+ KB
None

6. Clean Text Columns

In [21]:
# Remove leading and trailing spaces
df['OrderNumber'] = df['OrderNumber'].str.strip()

# Convert to uppercase for consistency
df['OrderNumber'] = df['OrderNumber'].str.upper()
df.head()

,OrderDate,StockDate,OrderNumber,ProductKey,CustomerKey,TerritoryKey,OrderLineItem,OrderQuantity
0,2020-01-01,2019-09-21,SO45080,332,14657,1,1,1
1,2020-01-01,2019-12-05,SO45079,312,29255,4,1,1
2,2020-01-01,2019-10-29,SO45082,350,11455,9,1,1
3,2020-01-01,2019-11-16,SO45081,338,26782,6,1,1
4,2020-01-02,2019-12-15,SO45083,312,14947,10,1,1

7. check unique categories

In [22]:
# Check unique values in categorical columns
unique_summary = pd.DataFrame({
    'Column': df.columns,
    'Unique_Count': [df[col].nunique() for col in df.columns],
    'Sample_Values': [df[col].unique()[:5] for col in df.columns]  
# first 5 unique values as sample
})

# Display summary
print(unique_summary)

          Column  Unique_Count  \
0      OrderDate           365
1      StockDate           446
2    OrderNumber          2630
3     ProductKey            44
4    CustomerKey          2630
5   TerritoryKey             8
6  OrderLineItem             1
7  OrderQuantity             1

                                       Sample_Values
0  [2020-01-01 00:00:00, 2020-01-02 00:00:00, 202...
1  [2019-09-21 00:00:00, 2019-12-05 00:00:00, 201...
2      [SO45080, SO45079, SO45082, SO45081, SO45083]
3                          [332, 312, 350, 338, 310]
4                [14657, 29255, 11455, 26782, 14947]
5                                   [1, 4, 9, 6, 10]
6                                                [1]
7                                                [1]

8. Remove unnecessary columns

In [24]:
df = df.drop(columns=['OrderLineItem', 'OrderNumber'])
df.columns

Index(['OrderDate', 'StockDate', 'ProductKey', 'CustomerKey', 'TerritoryKey',
       'OrderQuantity'],
      dtype='object')

9. Feature engineering

In [25]:
# yearly / monthly sales analysis
df['OrderYear'] = df['OrderDate'].dt.year
df['OrderMonth'] = df['OrderDate'].dt.month

# visual dashboards
df['OrderMonthName'] = df['OrderDate'].dt.month_name()

# days between stock and order.
df['ProcessingDays'] = (df['OrderDate'] - df['StockDate']).dt.days
df.columns

Index(['OrderDate', 'StockDate', 'ProductKey', 'CustomerKey', 'TerritoryKey',
       'OrderQuantity', 'OrderYear', 'OrderMonth', 'OrderMonthName',
       'ProcessingDays'],
      dtype='object')

10. Arrange columns

In [26]:
df = df[['OrderDate',
         'StockDate',
         'OrderYear',
         'OrderMonth',
         'OrderMonthName',
         'ProductKey',
         'CustomerKey',
         'TerritoryKey',
         'OrderQuantity',
         'ProcessingDays']]

df.head()

,OrderDate,StockDate,OrderYear,OrderMonth,OrderMonthName,ProductKey,CustomerKey,TerritoryKey,OrderQuantity,ProcessingDays
0,2020-01-01,2019-09-21,2020,1,January,332,14657,1,1,102
1,2020-01-01,2019-12-05,2020,1,January,312,29255,4,1,27
2,2020-01-01,2019-10-29,2020,1,January,350,11455,9,1,64
3,2020-01-01,2019-11-16,2020,1,January,338,26782,6,1,46
4,2020-01-02,2019-12-15,2020,1,January,312,14947,10,1,18

11. Outlier detection

In [27]:
Q1 = df['OrderQuantity'].quantile(0.25)
Q3 = df['OrderQuantity'].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = df[(df['OrderQuantity'] < lower_bound) | (df['OrderQuantity'] > upper_bound)]

print(outliers)

Empty DataFrame
Columns: [OrderDate, StockDate, OrderYear, OrderMonth, OrderMonthName, ProductKey, CustomerKey, TerritoryKey, OrderQuantity, ProcessingDays]
Index: []

12. Final Data Validation

In [30]:
# 1️.Check Missing Values
print(df.isnull().sum())

# 2.Check Duplicate Rows
print(df.duplicated().sum())

# 3.Reset Index After Row Removal
df = df.reset_index(drop=True)

# 4.Verify Final Dataset Shape
print(df.shape)

# 5.Data preview
print(df.head(5))

# 6.Save Cleaned Dataset
df.to_csv("Cleaned_Sales_Data.csv", index=False)

OrderDate         0
StockDate         0
OrderYear         0
OrderMonth        0
OrderMonthName    0
ProductKey        0
CustomerKey       0
TerritoryKey      0
OrderQuantity     0
ProcessingDays    0
dtype: int64
0
(2630, 10)
   OrderDate  StockDate  OrderYear  OrderMonth OrderMonthName  ProductKey  \
0 2020-01-01 2019-09-21       2020           1        January         332
1 2020-01-01 2019-12-05       2020           1        January         312
2 2020-01-01 2019-10-29       2020           1        January         350
3 2020-01-01 2019-11-16       2020           1        January         338
4 2020-01-02 2019-12-15       2020           1        January         312

   CustomerKey  TerritoryKey  OrderQuantity  ProcessingDays
0        14657             1              1             102
1        29255             4              1              27
2        11455             9              1              64
3        26782             6              1              46
4        14947            10              1              18